#!/bin/bash
CURRENT_IMAGE_PATH=$(gsettings get org.gnome.desktop.background picture-uri | gawk 'match($0, /(\/([a-zA-Z0-1\-\.]+\/)+[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-]+)/, a) {print a[1]}')
if [ ! -z "$CURRENT_IMAGE_PATH" ]
then
	CURRENT_IMAGE_EXPR="--filename=$CURRENT_IMAGE_PATH"
fi
NEW_IMAGE_PATH=$(zenity --file-selection --title="Choose a background image" --file-filter="All images | *.png *.jpg *.svg" --file-filter='PNG | *.png' --file-filter='JPG | *.jpg' --file-filter='SVG | *.svg' $CURRENT_IMAGE_EXPR)
if [ ! -z "$NEW_IMAGE_PATH" ]
then
	gsettings set org.gnome.desktop.background picture-uri file://$NEW_IMAGE_PATH
	echo "New selected background: $NEW_IMAGE_PATH"
fi
